name: Android Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 设置 JDK
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # 设置 Gradle 环境
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2

    # 授权 gradlew 执行权限
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    # 构建 APK
    - name: Build APK
      run: ./gradlew assembleDebug

    # 检查 APK 是否生成
    - name: List APK directory
      run: ls app/build/outputs/apk/debug/

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
