name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build APK with Buildozer
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          ccache \
          libncurses5:i386 \
          libstdc++6:i386 \
          libgtk2.0-0:i386 \
          libpangox-1.0-0:i386 \
          libpangoxft-1.0-0:i386 \
          zlib1g:i386 \
          openjdk-11-jdk \
          unzip \
          git \
          zip \
          python3-pip \
          python3-setuptools \
          python3-wheel \
          libffi-dev \
          libssl-dev \
          libtool \
          autoconf \
          automake \
          cmake \
          pkg-config \
          libncurses5-dev \
          libsqlite3-dev

        pip install --upgrade pip
        pip install cython virtualenv

    - name: Install Buildozer
      run: |
        pip install buildozer

    - name: Build the APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: brixpredictor-apk
        path: bin/*.apk
